#!/usr/bin/env bash
file_path=$(jq -r '.tool_input.file_path // empty')

for pattern in 'src/generated/' 'build/' 'coverage/' 'reports/' '.stryker-tmp/'; do
  case "$file_path" in
    *"$pattern"*)
      echo "Blocked: $file_path is generated by tooling. Do not hand-edit." >&2
      exit 2
      ;;
  esac
done
exit 0
